# -*- coding: utf-8 -*-
"""math4999_lsmc_cont_everything_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ydyx8Rxm3PoUDVsiWYoimqTFvwXZVfEf
"""

import matplotlib.pyplot as plt
import numpy as np

# ============================================================
# PARAMETERS
# ============================================================
face_value = 1000
conversion_price = 50
conversion_ratio = face_value / conversion_price
r = 0.05              # risk-free rate
q = 0.02              # dividend yield
T = 1.0
M = 1000              # time steps for Monte Carlo
dt = T / M
coupon_rate = 0.04
N = 10000             # number of MC paths
sigma = 0.2
S0 = 50

# ============================================================
# BASIS FUNCTIONS
# ============================================================
def quadratic_basis(S):
    return np.vstack([np.ones(len(S)), S, S**2]).T

def rational_basis(S):
    return np.vstack([
        np.ones(len(S)),
        S,
        S**2,
        1 / (1 + S),
        1 / (1 + S**2)
    ]).T

# ============================================================
# MONTE CARLO SIMULATION
# ============================================================
np.random.seed(0)
Z = np.random.standard_normal((N, M))
S = np.zeros((N, M + 1))
S[:, 0] = S0

for t in range(1, M + 1):
    S[:, t] = S[:, t-1] * np.exp(
        (r - q - 0.5 * sigma**2) * dt +
        sigma * np.sqrt(dt) * Z[:, t-1]
    )

# ============================================================
# INITIAL PAYOFFS AT MATURITY
# ============================================================
bond_values_quad = np.maximum(face_value, conversion_ratio * S[:, -1])
bond_values_rat = bond_values_quad.copy()

# EXERCISE BOUNDARIES
exercise_boundary_quad = np.zeros(M + 1)
exercise_boundary_rat = np.zeros(M + 1)
exercise_boundary_union = np.zeros(M + 1)
exercise_boundary_intersection = np.zeros(M + 1)

# DIAGNOSTICS
r2_quad = np.zeros(M)
aic_quad = np.zeros(M)
r2_rat = np.zeros(M)
aic_rat = np.zeros(M)

# ============================================================
# BACKWARD INDUCTION (LSM)
# ============================================================
for t in range(M - 1, -1, -1):

    accrued_coupons = coupon_rate * dt * face_value
    discount_factor = np.exp(-r * dt)

    discounted_bond_values_quad = discount_factor * bond_values_quad + accrued_coupons
    discounted_bond_values_rat = discount_factor * bond_values_rat + accrued_coupons

    Y_quad = discounted_bond_values_quad
    Y_rat = discounted_bond_values_rat
    S_t = S[:, t]

    # ----------------------------
    # Quadratic regression
    # ----------------------------
    X_quad = quadratic_basis(S_t)
    coeffs_quad, _, _, _ = np.linalg.lstsq(X_quad, Y_quad, rcond=None)
    cont_val_quad = X_quad @ coeffs_quad

    ss_res_quad = np.sum((Y_quad - cont_val_quad)**2)
    ss_tot_quad = np.sum((Y_quad - np.mean(Y_quad))**2)
    r2_quad[t] = 1 - ss_res_quad/ss_tot_quad if ss_tot_quad > 0 else 0
    n, k = X_quad.shape
    aic_quad[t] = n*np.log(ss_res_quad/n) + 2*k if ss_res_quad > 0 else np.nan

    # ----------------------------
    # Rational regression
    # ----------------------------
    X_rat = rational_basis(S_t)
    coeffs_rat, _, _, _ = np.linalg.lstsq(X_rat, Y_rat, rcond=None)
    cont_val_rat = X_rat @ coeffs_rat

    ss_res_rat = np.sum((Y_rat - cont_val_rat)**2)
    ss_tot_rat = np.sum((Y_rat - np.mean(Y_rat))**2)
    r2_rat[t] = 1 - ss_res_rat/ss_tot_rat if ss_tot_rat > 0 else 0
    n, k = X_rat.shape
    aic_rat[t] = n*np.log(ss_res_rat/n) + 2*k if ss_res_rat > 0 else np.nan

    # ----------------------------
    # EARLY CONVERSION DECISIONS
    # ----------------------------
    conversion_values = conversion_ratio * S_t

    # Quadratic
    exercise_quad = conversion_values >= cont_val_quad
    bond_values_quad = np.where(exercise_quad, conversion_values, discounted_bond_values_quad)

    # Rational
    exercise_rat = conversion_values >= cont_val_rat
    bond_values_rat = np.where(exercise_rat, conversion_values, discounted_bond_values_rat)

    # Boundaries
    hold_quad = np.where(~exercise_quad)[0]
    exercise_boundary_quad[t] = np.max(S_t[hold_quad]) if len(hold_quad) > 0 else 0

    hold_rat = np.where(~exercise_rat)[0]
    exercise_boundary_rat[t] = np.max(S_t[hold_rat]) if len(hold_rat) > 0 else 0

    hold_union = np.where(~(exercise_quad | exercise_rat))[0]
    exercise_boundary_union[t] = np.max(S_t[hold_union]) if len(hold_union) > 0 else 0

    hold_intersection = np.where(~(exercise_quad & exercise_rat))[0]
    exercise_boundary_intersection[t] = np.max(S_t[hold_intersection]) if len(hold_intersection) > 0 else 0

# Set maturity boundaries
exercise_boundary_quad[-1] = conversion_price
exercise_boundary_rat[-1] = conversion_price
exercise_boundary_union[-1] = conversion_price
exercise_boundary_intersection[-1] = conversion_price

# Monte Carlo prices
price_quad = np.mean(bond_values_quad) * np.exp(-r * dt)
price_rat = np.mean(bond_values_rat) * np.exp(-r * dt)

# ============================================================
# LATTICE CONVERTIBLE BOND TREE
# ============================================================

def trinomial_tree_convertible_vectorized(
    S0, face_value, conversion_price, r, q, sigma, T, n, coupon_rate, lam=1.0
):
    dt = T / n
    v = lam * sigma * np.sqrt(dt)

    # Probabilities (user formula)
    pu = 1/(2*lam**2) + (r - q - 0.5*sigma**2)*np.sqrt(dt)/(2*lam*sigma)
    pd = 1/(2*lam**2) - (r - q - 0.5*sigma**2)*np.sqrt(dt)/(2*lam*sigma)
    pm = 1 - 1/(lam**2)

    discount = np.exp(-r * dt)
    coupon = coupon_rate * dt * face_value
    conv_ratio = face_value / conversion_price

    # STOCK PRICES at maturity
    j = np.arange(-n, n+1)
    S_T = S0 * np.exp(v * j)

    # Bond payoff at maturity
    values = np.maximum(face_value, conv_ratio * S_T)

    # BACKWARD INDUCTION
    for step in range(n, 0, -1):
        cont = discount * (
            pu * values[2:] +
            pm * values[1:-1] +
            pd * values[0:-2]
        ) + coupon

        # Stock prices at this step
        j = np.arange(-(step-1), step)
        S_t = S0 * np.exp(v * j)

        conv_val = conv_ratio * S_t

        values = np.maximum(np.maximum(cont, conv_val), face_value)

    return values[0]

# ============================================================
# BENCHMARK PRICE
# ============================================================
benchmark_price = trinomial_tree_convertible_vectorized(
    S0, face_value, conversion_price, r, q, sigma, T,
    n=200,      # good accuracy, fast
    coupon_rate=coupon_rate,
    lam=1.0
)

# Percent errors
percent_error_quad = abs(price_quad - benchmark_price) / benchmark_price * 100
percent_error_rat = abs(price_rat - benchmark_price) / benchmark_price * 100

# ============================================================
# PRINT RESULTS
# ============================================================
print(f"Price (Quadratic basis): {price_quad:.4f}")
print(f"Price (Rational basis): {price_rat:.4f}")
print(f"Benchmark price (Trinomial tree): {benchmark_price:.4f}")
print(f"Percent error Quadratic: {percent_error_quad:.4f}%")
print(f"Percent error Rational: {percent_error_rat:.4f}%")

# ============================================================
# PLOTS
# ============================================================
S_max = np.max(S)
times = np.linspace(0, T, M + 1)

plt.figure(figsize=(15, 12))

# Quadratic boundary
plt.subplot(3, 1, 1)
plt.plot(times, exercise_boundary_quad, color='blue')
plt.fill_between(times, exercise_boundary_quad, S_max, color='blue', alpha=0.1)
plt.title('Exercise Boundary - Quadratic Basis')
plt.xlabel('Time')
plt.ylabel('Stock Price')
plt.grid(True)

# Rational boundary
plt.subplot(3, 1, 2)
plt.plot(times, exercise_boundary_rat, color='red')
plt.fill_between(times, exercise_boundary_rat, S_max, color='red', alpha=0.1)
plt.title('Exercise Boundary - Rational Basis')
plt.xlabel('Time')
plt.ylabel('Stock Price')
plt.grid(True)

# Union boundary
plt.subplot(3, 1, 3)
plt.plot(times, exercise_boundary_union, color='green')
plt.fill_between(times, exercise_boundary_union, S_max, color='green', alpha=0.1)
plt.title('Exercise Boundary - Union')
plt.xlabel('Time')
plt.ylabel('Stock Price')
plt.grid(True)

plt.tight_layout()
plt.show()


# Diagnostics
times_diag = np.linspace(0, T, M)
plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
plt.plot(times_diag, r2_quad, label='Quadratic')
plt.plot(times_diag, r2_rat, label='Rational')
plt.xlabel('Time'); plt.ylabel('R²'); plt.title('R² over time')
plt.legend(); plt.grid(True)

plt.subplot(1,2,2)
plt.plot(times_diag, aic_quad, label='Quadratic')
plt.plot(times_diag, aic_rat, label='Rational')
plt.xlabel('Time'); plt.ylabel('AIC'); plt.title('AIC over time')
plt.legend(); plt.grid(True)

plt.tight_layout()
plt.show()